### ISSUE TITLE
Best practice on dates 

### ISSUE THREAD

**Issue by rettinghaus** [TEI-Correspondence-SIG/CMIF#16]
Should letters of unknown date carry a _Terminus ante / post quem_, i.e. the dates of birth and death of the sender, or should that be done while analyzing by other services like correspSearch through authority control?

**Comment by peterstadler** [comment]
Good point. I'd say, the more you (as the editor of the letter) can express about that letter the better. (Better than any third person inferring from other sources.)

**Comment by StefanDumont** [comment]
Yes, I agree. The scholarly edition or the scholar should provide as many data as possible. A "Terminus ante / post quem" should be provided. Otherwise web services et al. would display the letter long before / after the period, where the letter has could been send. An automatic solution would be error-prone.
